config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'greeter/hello' => "greeter#hello"
  get 'greeter/goodbye'

    root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coursera.rb
# require 'httparty'

class Coursera
  include HTTParty

  default_options.update(verify: false) # Turn off SSL verification
  base_uri 'https://api.coursera.org/api/catalog.v1/courses'
  default_params fields: "smallIcon,shortDescription", q: "search"
  format :json

  def self.for term
    get("", query: { query: term})["elements"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @search_term ='jhu'
    @courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_names=["Alex", "Joe", "Michael"]
    @name = random_names.sample
    @time = Time.now
    @times_displayed ||=0
    @times_displayed +=1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
  def formatted_time(time)
    time.strftime("%I:%M%p")
  end
end

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term %></h1>

<table border="1">
  <tr>
  	<th>Image</th>
  	<th>Name</th>
  	<th>Description</th>
  </tr>
  <% @courses.each do |course| %>
    <tr class=<%= cycle('even', 'odd') %>>
      <td><%= image_tag(course["smallIcon"])%></td>
      <td><%= course["name"] %></td>
      <td><%= course["shortDescription"] %></td>
    </tr>
  <% end %>
</table>

app/views/greeter/goodbye.html.erb
<h1>Goodbye</h1>

app/views/greeter/hello.html.erb
<h1>Greeter <%= @name%></h1>
<p>Time now is <%= formatted_time(@time)%></p>
<p> This page has been viewed <%= @times_displayed%> time(s)</p>
<p><%= link_to "Google", "http://www.google.com"%></p>
<p><%= link_to "Goodbye", greeter_goodbye_path%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>